package com.briggin.footballfinder

import androidx.annotation.DrawableRes

enum class FlagRes(@DrawableRes val resID: Int, vararg val keys: String) {
    Abkhazia(R.drawable.abkhazia),
    Afghanistan(R.drawable.afghanistan, "Afghan", "afghanistan"),
    Aland(R.drawable.aland),
    Albania(R.drawable.albania, "Albanian", "albania"),
    Algeria(R.drawable.algeria, "Algerian", "algeria"),
    AmericanSamoa(R.drawable.american_samoa, "American Samoan", "american_Samoa"),
    Andorra(R.drawable.andorra, "Andorran", "andorra"),
    Angola(R.drawable.angola, "Angolan", "angola"),
    Antarctica(R.drawable.antarctica),
    AntiguaAndBarbuda(R.drawable.antigua_and_barbuda, "Antiguan", "antigua_and_barbuda", "Antigua and Barbuda"),
    Argentina(R.drawable.argentina, "Argentine", "argentina"),
    Armenia(R.drawable.armenia, "Armenian", "armenia"),
    Aruba(R.drawable.aruba, "Aruban", "aruba"),
    Australia(R.drawable.australia, "Australian", "australia"),
    Austria(R.drawable.austria, "Austrian", "austria"),
    Azerbaijan(R.drawable.azerbaijan, "Azerbaijani", "azerbaijan"),
    Bahamas(R.drawable.bahamas, "Bahamian", "bahamas"),
    Bahrain(R.drawable.bahrain, "Bahraini", "bahrain"),
    Bangladesh(R.drawable.bangladesh, "Bangladeshi", "bangladesh"),
    Barbados(R.drawable.barbados, "Barbadian", "barbados"),
    BasqueCountry(R.drawable.basque_country, "Basque Country", "basque_country"),
    Belarus(R.drawable.belarus, "Belarusian", "belarus", "Belgium"),
    Belgium(R.drawable.belgium, "Belgian", "belgium"),
    Belize(R.drawable.belize, "Belizean", "belize"),
    Benin(R.drawable.benin, "Beninese", "benin"),
    Bermuda(R.drawable.bermuda, "Bermudian", "bermuda"),
    Bhutan(R.drawable.bhutan, "Bhutanese", "bhutan"),
    Bolivia(R.drawable.bolivia, "Bolivian", "bolivia", "Bolivia"),
    BosniaAndHerzegovina(R.drawable.bosnia_and_herzegovina, "Bosnian", "bosnia_and_herzegovina", "Bosnia and Herzegovina"),
    Botswana(R.drawable.botswana, "Botswanan", "botswana"),
    Brazil(R.drawable.brazil, "Brazilian", "brazil"),
    BritishAntarcticTerritory(R.drawable.british_antarctic_territory),
    BritishVirginIslands(R.drawable.british_virgin_islands, "British Virgin Islander", "british_virgin_islands"),
    Brunei(R.drawable.brunei, "Bruneian", "brunei"),
    Bulgaria(R.drawable.bulgaria, "Bulgarian", "bulgaria"),
    BurkinaFaso(R.drawable.burkina_faso, "Burkinabe", "burkina_Faso", "Burkina Faso"),
    Burundi(R.drawable.burundi, "Burundian", "burundi"),
    Cambodia(R.drawable.cambodia, "Cambodian", "cambodia"),
    Cameroon(R.drawable.cameroon, "Cameroonian", "cameroon"),
    Canada(R.drawable.canada, "Canadian", "canada"),
    CanaryIslands(R.drawable.canary_islands, "Caymanian", "cayman_islands", "Canary Islands"),
    CapeVerde(R.drawable.cape_verde, "Cape Verde", "cape_verde"),
    CaymanIslands(R.drawable.cayman_islands, "Cayman Islands", "cayman_islands"),
    CentralAfricanRepublic(R.drawable.central_african_republic, "Central African", "central_african_republic", "Central African R"),
    Chad(R.drawable.chad, "Chadian", "chad"),
    Chile(R.drawable.chile, "Chilean", "chile"),
    China(R.drawable.china, "Chinese", "china", "Tibet", "China"), // Unfortunately
    ChristmasIsland(R.drawable.christmas_island),
    CocosKeelingIslands(R.drawable.cocos_keeling_islands),
    Colombia(R.drawable.colombia, "Colombian", "colombia"),
    Commonwealth(R.drawable.commonwealth),
    Comoros(R.drawable.comoros, "Comoran", "comoros"),
    CookIslands(R.drawable.cook_islands, "Cook Islander", "cook_islands"),
    CostaRica(R.drawable.costa_rica, "Costa Rican", "costa_rica", "Costa Rica"),
    CoteDivoire(R.drawable.cote_divoire, "Ivorian", "cote_divoire", "Ivory Coast"),
    Croatia(R.drawable.croatia, "Croatian", "croatia"),
    Cuba(R.drawable.cuba, "Cuban", "cuba"),
    Curacao(R.drawable.curacao, "Curaçaoan", "curacao", "Curaçao"),
    Cyprus(R.drawable.cyprus, "Cypriot", "cyprus"),
    CzechRepublic(R.drawable.czech_republic, "Czech", "czech_republic", "Czech Republic"),
    DemocraticRepublicOfTheCongo(R.drawable.democratic_republic_of_the_congo, "Congolese (DRC)", "democratic_republic_of_the_congo", "Congo", "DR Congo"),
    Denmark(R.drawable.denmark, "Danish", "denmark"),
    Djibouti(R.drawable.djibouti, "Djiboutian", "djibouti"),
    Dominica(R.drawable.dominica, "Dominican", "dominica"),
    DominicanRepublic(R.drawable.dominican_republic, "Dominican Republic", "dominican_republic"),
    EastTimor(R.drawable.east_timor, "East Timor", "east_timor"),
    Ecuador(R.drawable.ecuador, "Ecuadorian", "ecuador"),
    Egypt(R.drawable.egypt, "Egyptian", "egypt"),
    ElSalvador(R.drawable.el_salvador, "El Salvador", "el_salvador"),
    England(R.drawable.england, "English", "england", "England"),
    EquatorialGuinea(R.drawable.equatorial_guinea, "Equatoguinean", "equatorial_guinea", "Equatorial Guinea"),
    Eritrea(R.drawable.eritrea, "Eritrean", "eritrea"),
    Estonia(R.drawable.estonia, "Estonian", "estonia"),
    EuropeanUnion(R.drawable.european_union),
    FalklandIslands(R.drawable.falkland_islands),
    Faroes(R.drawable.faroes, "Faroese", "faroes", "Faroe Islands"),
    Fiji(R.drawable.fiji, "Fijian", "fiji"),
    Finland(R.drawable.finland, "Finnish", "finland"),
    France(R.drawable.france, "French", "france", "France", "Réunion"),
    FrenchGuiana(R.drawable.french_guiana, "French Guiana", "french_guiana"),
    FrenchPolynesia(R.drawable.french_polynesia),
    FrenchSouthernTerritories(R.drawable.french_southern_territories),
    Gabon(R.drawable.gabon, "Gabonese", "gabon"),
    Gambia(R.drawable.gambia, "Gambian", "gambia"),
    Georgia(R.drawable.georgia, "Georgian", "georgia"),
    Germany(R.drawable.germany, "German", "germany", "Germany"),
    Ghana(R.drawable.ghana, "Ghanaian", "ghana"),
    Gibraltar(R.drawable.gibraltar, "Gibraltarian", "gibraltar"),
    Gosquared(R.drawable.gosquared),
    Greece(R.drawable.greece, "Greek", "greece"),
    Greenland(R.drawable.greenland),
    Grenada(R.drawable.grenada, "Grenadian", "grenada"),
    Guadeloupe(R.drawable.guadeloupe),
    Guam(R.drawable.guam, "Guamanian", "guam"),
    Guatemala(R.drawable.guatemala, "Guatemalan", "guatemala"),
    Guernsey(R.drawable.guernsey),
    Guinea(R.drawable.guinea, "Guinean", "guinea"),
    GuineaBissau(R.drawable.guinea_bissau, "Guinean (Bissau)", "guinea_bissau"),
    Guyana(R.drawable.guyana, "Guyanese", "guyana"),
    Haiti(R.drawable.haiti, "Haitian", "haiti"),
    Honduras(R.drawable.honduras, "Honduran", "honduras"),
    HongKong(R.drawable.hong_kong, "Hong Kong", "hong_kong"),
    Hungary(R.drawable.hungary, "Hungarian", "hungary"),
    Iceland(R.drawable.iceland, "Icelandic", "iceland"),
    India(R.drawable.india, "Indian", "india"),
    Indonesia(R.drawable.indonesia, "Indonesian", "indonesia"),
    Iran(R.drawable.iran, "Iranian", "iran"),
    Iraq(R.drawable.iraq, "Iraqi", "iraq"),
    Ireland(R.drawable.ireland, "Irish", "ireland", "Ireland", "Republic of Ireland"),
    IsleOfMan(R.drawable.isle_of_man),
    Israel(R.drawable.israel, "Israeli", "israel"),
    Italy(R.drawable.italy, "Italian", "italy"),
    Jamaica(R.drawable.jamaica, "Jamaican", "jamaica"),
    Japan(R.drawable.japan, "Japanese", "japan"),
    Jersey(R.drawable.jersey),
    Jordan(R.drawable.jordan, "Jordanian", "jordan"),
    Kazakhstan(R.drawable.kazakhstan),
    Kenya(R.drawable.kenya, "Kenyan", "kenya"),
    Kiribati(R.drawable.kiribati),
    Kosovo(R.drawable.kosovo, "Kosovar", "kosovo"),
    Kuwait(R.drawable.kuwait, "Kuwaiti", "kuwait"),
    Kyrgyzstan(R.drawable.kyrgyzstan, "Kyrgyzstani", "kyrgyzstan"),
    Laos(R.drawable.laos, "Laotian", "laos"),
    Latvia(R.drawable.latvia, "Latvian", "latvia"),
    Lebanon(R.drawable.lebanon, "Lebanese", "lebanon"),
    Lesotho(R.drawable.lesotho, "Basotho", "lesotho"),
    Liberia(R.drawable.liberia, "Liberian", "liberia"),
    Libya(R.drawable.libya, "Libyan", "libya"),
    Liechtenstein(R.drawable.liechtenstein, "Liechtenstein", "liechtenstein"),
    Lithuania(R.drawable.lithuania, "Lithuanian", "lithuania"),
    Luxembourg(R.drawable.luxembourg),
    Macau(R.drawable.macau, "Macanese", "macau"),
    Macedonia(R.drawable.macedonia, "Macedonian", "macedonia"),
    Madagascar(R.drawable.madagascar, "Malagasy", "madagascar"),
    Malawi(R.drawable.malawi, "Malawian", "malawi"),
    Malaysia(R.drawable.malaysia, "Malaysian", "malaysia"),
    Maldives(R.drawable.maldives, "Maldivian", "maldives"),
    Mali(R.drawable.mali, "Malian", "mali"),
    Malta(R.drawable.malta, "Maltese", "malta"),
    Mars(R.drawable.mars),
    MarshallIslands(R.drawable.marshall_islands),
    Martinique(R.drawable.martinique, "Martinica", "martinique", "Martiniquais"),
    Mauritania(R.drawable.mauritania, "Mauritanian", "mauritania"),
    Mauritius(R.drawable.mauritius, "Mauritian", "mauritius"),
    Mayotte(R.drawable.mayotte, "Mahoran", "mayotte"),
    Mexico(R.drawable.mexico, "Mexico", "mexico", "Mexican"),
    Micronesia(R.drawable.micronesia),
    Moldova(R.drawable.moldova, "Moldovan", "moldova"),
    Monaco(R.drawable.monaco),
    Mongolia(R.drawable.mongolia, "Mongolian", "mongolia"),
    Montenegro(R.drawable.montenegro, "Montenegrin", "montenegro"),
    Montserrat(R.drawable.montserrat, "Montserratian", "montserrat"),
    Morocco(R.drawable.morocco, "Moroccan", "morocco"),
    Mozambique(R.drawable.mozambique, "Mozambican", "mozambique"),
    Myanmar(R.drawable.myanmar, "Burmese", "myanmar"),
    NagornoKarabakh(R.drawable.nagorno_karabakh),
    Namibia(R.drawable.namibia, "Namibian", "namibia"),
    Nato(R.drawable.nato),
    Nauru(R.drawable.nauru),
    Nepal(R.drawable.nepal, "Nepali", "nepal"),
    Netherlands(R.drawable.netherlands, "Dutch", "netherlands"),
    NetherlandsAntilles(R.drawable.netherlands_antilles, "Netherlands Antilles", "netherlands_antilles"),
    NewCaledonia(R.drawable.new_caledonia, "New Caledonia", "new_caledonia", "New Caledonian"),
    NewZealand(R.drawable.new_zealand, "New Zealand", "new_zealand", "New Zealand"),
    Nicaragua(R.drawable.nicaragua, "Nicaraguan", "nicaragua"),
    Nigeria(R.drawable.nigeria, "Nigerian", "nigeria", "Nigerien"),
    Niue(R.drawable.niue),
    NorfolkIsland(R.drawable.norfolk_island),
    NorthKorea(R.drawable.north_korea, "North Korea", "north_korea", "North Korean"),
    NorthernCyprus(R.drawable.northern_cyprus, "Northern Cyprus", "northern_cyprus"),
    NorthernIreland(R.drawable.northern_ireland, "Northern Ireland", "northern_ireland", "Northern Irish"),
    NorthernMarianaIslands(R.drawable.northern_mariana_islands, "Northern Mariana", "northern_mariana_islands"),
    Norway(R.drawable.norway, "Norwegian", "norway"),
    Olympics(R.drawable.olympics),
    Oman(R.drawable.oman, "Omani", "oman"),
    Pakistan(R.drawable.pakistan),
    Palau(R.drawable.palau),
    Palestine(R.drawable.palestine),
    Panama(R.drawable.panama),
    PapuaNewGuinea(R.drawable.papua_new_guinea, "Papua New Guinea", "papua_new_guinea"),
    Paraguay(R.drawable.paraguay),
    Peru(R.drawable.peru),
    Philippines(R.drawable.philippines),
    PitcairnIslands(R.drawable.pitcairn_islands),
    Poland(R.drawable.poland),
    Portugal(R.drawable.portugal),
    PuertoRico(R.drawable.puerto_rico, "Puerto Rico", "puerto_rico"),
    Qatar(R.drawable.qatar),
    RedCross(R.drawable.red_cross),
    RepublicOfTheCongo(R.drawable.republic_of_the_congo, "Congolese", "republic_of_the_congo"),
    Romania(R.drawable.romania),
    Russia(R.drawable.russia),
    Rwanda(R.drawable.rwanda),
    SaintBarthelemy(R.drawable.saint_barthelemy),
    SaintHelena(R.drawable.saint_helena),
    SaintKittsAndNevis(R.drawable.saint_kitts_and_nevis, "Kittitian", "saint_kitts_and_nevis", "Saint Kitts and Nevis"),
    SaintLucia(R.drawable.saint_lucia, "Saint Lucia", "saint_lucia"),
    SaintMartin(R.drawable.saint_martin),
    SaintVincentAndTheGrenadines(R.drawable.saint_vincent_and_the_grenadines, "Saint Vincent", "saint_vincent_and_the_grenadines"),
    Samoa(R.drawable.samoa),
    SanMarino(R.drawable.san_marino, "San Marino", "san_marino"),
    SaoTomeAndPrincipe(R.drawable.sao_tome_and_principe, "São Tomé and Príncipe", "sao_tome_and_principe"),
    SaudiArabia(R.drawable.saudi_arabia, "Saudi Arabia", "saudi_arabia"),
    Scotland(R.drawable.scotland),
    Senegal(R.drawable.senegal),
    Serbia(R.drawable.serbia),
    Seychelles(R.drawable.seychelles),
    SierraLeone(R.drawable.sierra_leone, "Sierra Leone", "sierra_leone"),
    Singapore(R.drawable.singapore),
    Slovakia(R.drawable.slovakia),
    Slovenia(R.drawable.slovenia),
    SolomonIslands(R.drawable.solomon_islands, "Solomon Islands", "solomon_islands"),
    Somalia(R.drawable.somalia),
    Somaliland(R.drawable.somaliland),
    SouthAfrica(R.drawable.south_africa, "South Africa", "south_africa"),
    SouthGeorgiaAndTheSouthSandwichIslands(R.drawable.south_georgia_and_the_south_sandwich_islands),
    SouthKorea(R.drawable.south_korea, "South Korea", "south_korea"),
    SouthOssetia(R.drawable.south_ossetia),
    SouthSudan(R.drawable.south_sudan),
    Spain(R.drawable.spain),
    SriLanka(R.drawable.sri_lanka, "Sri Lanka", "sri_lanka"),
    Sudan(R.drawable.sudan),
    Suriname(R.drawable.suriname),
    Swaziland(R.drawable.swaziland),
    Sweden(R.drawable.sweden),
    Switzerland(R.drawable.switzerland),
    Syria(R.drawable.syria),
    Tahiti(R.drawable.tahiti),
    Taiwan(R.drawable.taiwan, "Chinese Taipei", "taiwan"),
    Tajikistan(R.drawable.tajikistan),
    Tanzania(R.drawable.tanzania, "Zanzibar", "tanzania"),
    Thailand(R.drawable.thailand),
    Togo(R.drawable.togo),
    Tokelau(R.drawable.tokelau),
    Tonga(R.drawable.tonga),
    TrinidadAndTobago(R.drawable.trinidad_and_tobago, "Trinidad and Tobago", "trinidad_and_tobago"),
    Tunisia(R.drawable.tunisia),
    Turkey(R.drawable.turkey),
    Turkmenistan(R.drawable.turkmenistan),
    TurksAndCaicosIslands(R.drawable.turks_and_caicos_islands, "Turks & Caicos Islands", "turks_and_caicos_islands"),
    Tuvalu(R.drawable.tuvalu),
    Uganda(R.drawable.uganda),
    Ukraine(R.drawable.ukraine),
    UnitedArabEmirates(R.drawable.united_arab_emirates, "Emirati", "united_arab_emirates", "United Arab Emirates"),
    UnitedKingdom(R.drawable.united_kingdom),
    UnitedNations(R.drawable.united_nations),
    UnitedStates(R.drawable.united_states, "American", "united_states", "United States"),
    Unknown(R.drawable.unknown),
    Uruguay(R.drawable.uruguay),
    UsVirginIslands(R.drawable.us_virgin_islands),
    Uzbekistan(R.drawable.uzbekistan),
    Vanuatu(R.drawable.vanuatu, "Ni_Vanuatu", "vanuatu"),
    VaticanCity(R.drawable.vatican_city),
    Venezuela(R.drawable.venezuela),
    Vietnam(R.drawable.vietnam),
    Wales(R.drawable.wales),
    WallisAndFutuna(R.drawable.wallis_and_futuna, "Wallis & Futuna", "wallis_and_futuna"),
    WesternSahara(R.drawable.western_sahara),
    Vemen(R.drawable.yemen),
    Zambia(R.drawable.zambia),
    Zimbabwe(R.drawable.zimbabwe);

    companion object {
        fun fromKey(key: String) = values().find { it.keys.contains(key) } ?: Unknown
    }
}
